version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_DEBUG=false
      - APP_BASE_URL=http://localhost:8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - EMAIL_ENABLED=false
    volumes:
      - ./db:/app/db
      - ./log:/app/log
      - ./misc/templates/pfp:/app/misc/templates/pfp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db_data:
  log_data:
  pfp_data:
